name: Tests
on:
  push:
    branches:
      - master
jobs:

# Unit tests back (phpunit)
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.4
            env:
              LARAVEL: 7.*
              TESTBENCH: 5.*
          - php: 7.4
            env:
              LARAVEL: 8.*
              TESTBENCH: 6.*
          - php: 8.0
            env:
              LARAVEL: 7.*
              TESTBENCH: 5.*
          - php: 8.0
            env:
              LARAVEL: 8.*
              TESTBENCH: 6.*
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, mysql
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update --prefer-dist
          composer update --prefer-stable --prefer-dist --no-interaction
      - name: Execute tests via PHPUnit
        run: ./vendor/bin/phpunit
      - uses: 8398a7/action-slack@v3
#        if: failure()
        with:
          status: ${{ job.status }}
          fields: job, message, author
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}